[tools]
java = "17"
node = "latest"
python = "latest"
uv = "latest"

[tasks.kctx]
description = "Lisa context"
run = "kubectl config get-contexts"

[tasks.kpods]
description = "Lisa todos os pods"
run = "kubectl get pods -A"

